### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by AFONSOCMG** [popcorn-official/popcorn-android#260]
Version: 0.2.9
Download date:24/07/2017
Android version:5.1.1 

#### Expected Behaviour

...
I thought that the app was a great idea 
#### Actual Behaviour

...
I can't put subtitles, because it always says "loading subtitles", and when I put in the predefined video player popcorn time's video player and I put play movie the app turns off.
### Steps to repoduce the behaviour

I don't know.
1. ...
2. ...
3. ...

**Comment by dmi87** [comment]
Same Problem

**Comment by dmi87** [comment]
Hello,

Why do you close when no info is given. Can you tell me wath the problem is and if there is a solution in the making?

Regards

Verzonden door TypeApp<http://www.typeapp.com/r?b=10189>
Op 28 jul. 2017, om 13:56, Chris Alderson <notifications@github.com<mailto:notifications@github.com>> schreef:

Closed #260<https://github.com/popcorn-official/popcorn-android/issues/260>.

**Comment by AFONSOCMG** [comment]
Hello,Actually, it wasn't me who closed. I was surprised when I received an e-mail telling me that was closed. Can you  clarify me what happened?Enviado do meu telefone Huawei.-------- Mensagem original --------Assunto: Re: [popcorn-official/popcorn-android] Subtitles (#260)De: dmi87 Para: popcorn-official/popcorn-android CC: AFONSOCMG ,Author Hello,



Why do you close when no info is given. Can you tell me wath the problem is and if there is a solution in the making?



Regards



Verzonden door TypeApp<http://www.typeapp.com/r?b=10189>

Op 28 jul. 2017, om 13:56, Chris Alderson <notifications@github.com<mailto:notifications@github.com>> schreef:



Closed #260<https://github.com/popcorn-official/popcorn-android/issues/260>.

**Comment by AFONSOCMG** [comment]
Hello,Can you tell me what's happening, because I didn't authorise nothing.I don't understand why my issue was closed.Can you help me?-------- Mensagem original --------Assunto: Re: [popcorn-official/popcorn-android] Subtitles (#260)De: Chris Alderson Para: popcorn-official/popcorn-android CC: AFONSOCMG ,Author Closed #260.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/popcorn-official/popcorn-android","title":"popcorn-official/popcorn-android","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/popcorn-official/popcorn-android"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #260."}],"action":{"name":"View Issue","url":"https://github.com/popcorn-official/popcorn-android/issues/260#event-1183392228"}}}

**Comment by dmi87** [comment]
Chris Alderson closed the topic where I ask if there is a problem with loading subtitles. I can't get subtitles anywhere.
And I asked there why there is no download button anymore,
Regards
Dimitri

Verzonden door TypeApp<http://www.typeapp.com/r?b=10189>
Op 29 jul. 2017, om 00:25, AFONSOCMG <notifications@github.com<mailto:notifications@github.com>> schreef:
Hello,Actually, it wasn't me who closed. I was surprised when I received an e-mail telling me that was closed. Can you clarify me what happened?Enviado do meu telefone Huawei.-------- Mensagem original --------Assunto: Re: [popcorn-official/popcorn-android] Subtitles (#260)De: dmi87 Para: popcorn-official/popcorn-android CC: AFONSOCMG ,Author Hello,



Why do you close when no info is given. Can you tell me wath the problem is and if there is a solution in the making?



Regards



Verzonden door TypeApp<http://www.typeapp.com/r?b=10189>

Op 28 jul. 2017, om 13:56, Chris Alderson <notifications@github.com<mailto:notifications@github.com>> schreef:



Closed #260<https://github.com/popcorn-official/popcorn-android/issues/260>.
