### ISSUE TITLE
No subtitles on Android TV version tv-armeabi-v7a-release-0.1.4.apk   

### ISSUE THREAD

**Issue by venzislav** [popcorn-official/popcorn-android#294]
Version:  0.1.4
Download date:  06.11.2017
Android version:  Android TV 6.0

#### Expected Behaviour
To have subtitles in the movies.

#### Actual Behaviour
No subtitles :(

#### Steps to repoduce the behaviour
Just start the aplication and run some movie.

Please fix it , I see that on linux desktop version all is ok but on android TV is broken !
And if I try to run latest development version it crashes !

**Comment by cangelosilima** [comment]
Same problem here

**Comment by isipka** [comment]
bump

**Comment by christianoguedes** [comment]
same

**Comment by isipka** [comment]
bump

**Comment by raphaelmro** [comment]
same here

**Comment by Persei08** [comment]
Can you try with the [dev build 138](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Android/138/)?
If PT crash when you launch it, retry by spamming the right button or right arrow key when you launch it. For me, if i do it quickly enough it don't crash. (Not great, but it allow me to use it)

**Comment by raphaelmro** [comment]
@Persei08 I've tried but it crashes(PT stops) when I select to watch the movie.

**Comment by Persei08** [comment]
@raphaelmro , Yes sorry, I was wrong :/

**Comment by LorneMalvoX** [comment]
Same problem here.

**Comment by Aaronlonin** [comment]
Issue happens to me with custom subtitles on any series/movies

**Comment by xupak** [comment]
Download the apk from popcorn-time.ch and install it on your tv. GL&HF

**Comment by Persei08** [comment]
@xupak popcorn-time.ch isn't related to this project, it another clone app.

People are free to do what they want but at least tell them it's not the same project and team

**Comment by xupak** [comment]
@Persei08 if they dont bother to fix it then why not use the community made one. Just trying to help, nothing else

**Comment by Persei08** [comment]
@xupak 
it's not the community made one. the community edition (CE) was at https://popcorntimece.ch. Here the link you provide seem to be the time4popcorn team (aka popcorn-time.to).

[They bother to fix it](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Android/changes) why else updating it. As far as I know there is just 2 devs in PT team, the others contributors are users who choose to contribute by fixing stuffs. Also development for android TV is the more painful because there isn't good android TV emulators.

**Comment by xupak** [comment]
@Persei08
My bad then
