### ISSUE TITLE
TV version restarts after clicking "Watch" button

### ISSUE THREAD

**Issue by jbogunia** [popcorn-official/popcorn-android#440]
Version:  0.1.4
Download date:  2018-12-18
Android version:  TV 7.0

#### Expected Behaviour

Watch selected movie

#### Actual Behaviour

After clicking "Watch" on movie preview fragment PopcornTime app restarts to main screen
Happens on build 159 from jenkins (https://ci.popcorntime.sh/job/Popcorn-Time-Android/159/)

#### Steps to repoduce the behaviour

1. Open PopcornTime app
2. Click on any movie
3. Click "Watch" button

**Comment by MrRory** [comment]
We're not supporting builds from Jenkins.

**Comment by jbogunia** [comment]
But this does not work on any TV app version
So @MrRory, where can I find builds which are supported? 
btw last github release was on 24 Oct 2016...

**Comment by MrRory** [comment]
The supported builds are the builds on [the website](https://get.popcorntime.sh/). I know the Android TV is pretty much broken. So I asked if it could be removed as download until someone fixes it.

**Comment by marbuser** [comment]
> We're not supporting builds from Jenkins.

You don't support builds of your own live code? I'm not here to be _that guy_. But you shouldn't be closing issues just because you "don't support them". You should be actually listening to what the issues are, and making a list so that when you DO go to fix stuff, you know what the most prominent issues are.

Otherwise, what is the point in even making this project Open Source? Or better yet, what's the point in even working on it if the app crashes as soon as you try to watch anything (Which is literally the entire purpose of the app.)

Again, I don't want to be _that guy_, but it's obvious if you guys have no intent to "support" builds of your own live code and just auto close all new issues that come in, you really should consider making it no longer open source or just no longer working on it if you are going to tell people you don't care if they are having problems...

**Comment by team-pct** [comment]
@marbuser CI version are very unstable so we cannot really give support on every build we make to test for a stable version

**Comment by marbuser** [comment]
> @marbuser CI version are very unstable so we cannot really give support on every build we make to test for a stable version
> Also if you can see we are as you said an open source project and not everyone is willing to just stop all what they have to find out why a dev build doesn't work
> 
> MrRory Quote
> 
> > The supported builds are the builds on the website. I know the Android TV is pretty much broken. So I asked if it could be removed as download until someone fixes it.

Sure, I completely understand that. Just to me at least, it doesn't feel like auto closing any issues relating to CI versions is the right way to go about it.

I completely get them being unstable and not giving support, but I think context definitely matters.
If say someone is saying something like; "There is something wrong with subtitles in the CI build", then I can completely understand that NOT getting support (but should still be left open until it is fixed). But if the issue is something like "The entire app literally doesn't work at all", that should be taken slightly more seriously I think.

To me at least, it also feels like issues should relate directly to the code that is on the repo. Since maybe you guys fix something that is broken in the stable/website version in the repo, but someone reports it again (even though it's not an issue anymore). It just causes a bit of a mess and is hard to maintain imo.

Anyway you guys run it however you like, I just think it's not very sensible to be auto closing all issues  that are related to CI Versions even if they are genuine issues.

**Comment by team-pct** [comment]
Man I understand your frustration , but understand ours ... we are very limited team trying doing our best when we have free time like now its xMAS ! so i wish you happy holidays

**Comment by MrRory** [comment]
>I just think it's not very sensible to be auto closing all issues that are related to CI Versions even if they are genuine issues.

That why #106 is still open.
