### ISSUE TITLE
Download Video & Video Subtitles Feature

### ISSUE THREAD

**Issue by sweatycorndog19000** [popcorn-official/popcorn-android#448]
Please add a feature in Popcorn Time (On all platforms) the ability to download a video and choose what video quality and an option to download video subtitles directly through the Popcorn Time app. This way no need for magnet links and this will allow for an easy and convent way to watch movies offline.

I know a magnet link can be used in a torrent client but Popcorn Time uses bittorrent so I would imagine it is not hard to add a download feature to the app which will save the video to a certain folder which the user can choose.

**Comment by MrRory** [comment]
> I would imagine it is not hard to add a download feature

Unfortunately it is. The library we use was specifically built to download _one_ video file sequentially so it cannot be used without large modifications to download a complete torrent. Torrent clients have completely different requirements on mobile platforms due to the internet and battery usage. That's why Popcorn Time doesn't have this capability, it's specifically for the 'streaming' usage.

**Comment by SscSPs** [comment]
Can we make download option for content that will be open in popcorn time only(or not) for viewing later?
