### ISSUE TITLE
Doesn't load subtitles

### ISSUE THREAD

**Issue by eelccoloo** [popcorn-official/popcorn-android#802]
Operating System Version:
android 11

Popcorn Time Version:
3.5

Download date:
04/07/2022

Download url:
popcorn-time.ga/build

#### Steps to reproduce the behaviour
install popcorn time 3.5 arm on one plus 8 with android 11

also i would be nice to be able to change api since there are movies that doesn't appear. and the search engine doesn't work really well. nevertheless some movies load correctly and although i didn't try i guess i could load the subtitles myself

**Comment by timrosu** [comment]
As I know opensubtitles.com for few years now requires that you create account and use the api.
Desktop version of Popcorn Time supports login but mobile version doesn't. I hope that changes soon.

**Comment by superbonaci** [comment]
Search results depend on what is the language of your device and popcorn itself, and also in what language you search the movie. For some movies it works using the english and for others the original title.

**Comment by minhtri09** [comment]
Yes. i saw the desktop version can login opensubtitles, but android version can't. Android version still not have update along time

**Comment by gnaoh1379** [comment]
same issue with latest version

**Comment by superbonaci** [comment]
> same issue with latest version
Did you try what I said in last post, changing the language of popcorn to the language of the movie? If you could post a sample movie pasted in here: https://controlc.com/

I could check if the same happens to me.

**Comment by KolTheBlack** [comment]
Yes is the same, the App is in english Language and the movie same language Inviato da Posta per Windows Da: superbonaciInviato: venerdì 6 gennaio 2023 13:33A: popcorn-official/popcorn-androidCc: KolTheBlack; ManualOggetto: Re: [popcorn-official/popcorn-android] Doesn't load subtitles (Issue #802) same issue with latest versionDid you try what I said in last post, changing the language of popcorn to the language of the movie? If you could post a sample movie pasted in here: https://controlc.com/I could check if the same happens to me.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by superbonaci** [comment]
@KolTheBlack if you tell me which movie it is I can check if subs load for me.

**Comment by KolTheBlack** [comment]
Well i try the Top Gun 2022 for example, so app in english, movie in
english, when a go to page of the movie is write Loading subtitle but never
loading subtitle, i start the movie then i go to choose subtitle and i get
no subtitle or custom subtitle, nothing else, thanks

Il Lun 9 Gen 2023, 21:47 superbonaci ***@***.***> ha scritto:
