### ISSUE TITLE
Error: No connection 

### ISSUE THREAD

**Issue by greekfanas** [popcorn-official/popcorn-android#829]
Before the update it was working fine but now everytime I open the apk nothing loads and it just says "no connection". I uninstalled it and reinstalled it, I restarted my phone and cleared the data but nothing happened.

**Comment by kiriles90** [comment]
Which update? What's your version number? Where did you download the app from?

**Comment by greekfanas** [comment]
I have downloaded 2 versions and I had the same problem 3.6.10 and 3.6.9
and I downloaded the 3.6.10 here and the 3.6.9 from the greek popcorntime...

Στις Τετ, 11 Ιαν 2023, 13:16 ο χρήστης kiriles90 ***@***.***>
έγραψε:

**Comment by kiriles90** [comment]
Both of those version are not the official app. Its the now possibly finally dead Time4Popcorn (though they said they will shut it down almost a year ago). For that, you'll have to get support in their own forum (in the case its not actually dead) since its basically a different app. The latest official version number is 0.3.6 and you can find it in the releases page here. Its API works fine so if you still cant access that one either it probably means your ISP is blocking the url in which case you'll have to use something like a DNS change (to google, cloudflare etc) or a VPN (that supports p2p) to bypass the block.  

Closing this issue since its not an issue with the official app but if you need anything else just comment below normally.
