### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by RameshGokamalla** [popcorn-official/popcorn-android#845]
There are no updates for very long time. I'm using this application these days often but there are few problems with it too. Few feature requests are there.
1) Application becomes not responsive after clicking a movie title. 🥶 
2) Doesn't play video properly even if I have strong interest connection.
3) Download and Watch feature is not there.
4) We can't see movie file size for the selected resolution. (Big impact on data saving)
5) missing Material You 3/Monet theme engine support

**Comment by kiriles90** [comment]
Yes its alive / has issues / is in need of regular developers but none seems to take it up. All true.
(as for me and Ivan we have our hands full with basically adopting the desktop app at this point, none helps there too, its an opensource project, none makes money of it, none owns it, none can be asked to fix anything, just help if they want to)

Closing this since not an actual issue but continue the conversation below freely if you want.
